### ISSUE TITLE
Try Jasmine link is no longer valid

### ISSUE THREAD

**Issue by kenirwin** [sparkbox/apprenticeships#24]
The "Try Jasmine" link in Phase 2 Additional Resources goes to http://tryjasmine.com ; unfortunately, that's now a porn site. 

I looked for an alternative, and one thing I found was this: 
http://try-jasmine.herokuapp.com/
I cannot immediately discern how that site works or if it might be similar to the old site, but I'll point out the flaw and hope you're able to replace the link with one that best represents what you're hoping to share.

**Comment by cromwellryan** [comment]
Thanks @kenirwin! That's super embarrassing! 😥
