### ISSUE TITLE
Improve Ruby setup guide

### ISSUE THREAD

**Issue by cromwellryan** [sparkbox/apprenticeships#8]
https://github.com/sparkbox/apprenticeships/blob/master/projects/proj-ruby-setup.md

**Comment by cromwellryan** [comment]
@yock - can you lead the apprentices through this when they get to it?

Do you think it's better to document it for them or have them document it?  I'm leaning toward the later since we're going to ask them to maintain this repo as part of the apprenticeship. Thoughts?

**Comment by yock** [comment]
I think we'd benefit from the apprentices documenting it. They're less likely to gloss over things we'd find trivial.

**Comment by cromwellryan** [comment]
:+1:
