### ISSUE TITLE
Provide basic training on the command line early within Phase 1

### ISSUE THREAD

**Issue by cromwellryan** [sparkbox/apprenticeships#9]
We ask the apprentices to learn git early in the apprenticeship, but we've also seen a gap in the command line experience/knowledge.  Somehow we need to account for this to some extent.

**Comment by cromwellryan** [comment]
@asimpson @yock @ethanmuller do you have any thoughts on how we can help here?

**Comment by yock** [comment]
Git isn't exactly the easiest tool to get familiar with, so teaching command line by teaching git probably introduces a lot of opportunities to forget what you've learned. Even first learning to navigate the directory tree without getting lost (`cd`, `ls`, `pwd`, etc...) would be a big confidence boost I think.

**Comment by cromwellryan** [comment]
I'm also thinking about the profile customization that we spent time on last round.  I wonder if that angle is best - showing them how to customize their command line experience and then letting that guide the lessons.

**Comment by asimpson** [comment]
Yeah I like the idea of using customization as the "way in". Though, there probably still needs to be a intro to basic navigation and actions like @yock was saying. Going basics -> customization also gives more context instead of just starting out with customization

**Comment by cromwellryan** [comment]
I feel like we do this pretty well now. Closin'

![](http://media0.giphy.com/media/xUPGcxD0h57OX2QXZK/200.gif)
